apiVersion: container.gcp.crossplane.io/v1beta1
kind: GKECluster
metadata:
  name: cluster-1
  namespace: default
  annotations:
    crossplane.io/external-name: cluster-1
spec:
  writeConnectionSecretToRef:
    name: cluster-1
    namespace: default
  forProvider: 
    location: us-central1-c
  providerRef: 
    name: gcp-provider